# Generated by Django 4.2.30 on 2026-04-23 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('cover_image_url', models.URLField(blank=True, default='')),
                ('theme_color', models.CharField(default='#F3B0C3', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZineCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_key', models.CharField(choices=[('cover', 'Cover'), ('back', 'Back'), ('page1', 'Page 1'), ('page2', 'Page 2'), ('page3', 'Page 3'), ('page4', 'Page 4'), ('page5', 'Page 5'), ('page6', 'Page 6')], max_length=10)),
                ('image_url', models.URLField(blank=True, default='')),
                ('cloudinary_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('text_content', models.TextField(blank=True, default='')),
                ('text_color', models.CharField(default='#1a1a1a', max_length=7)),
                ('font_size', models.IntegerField(default=16)),
                ('bg_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('zine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='zines.zine')),
            ],
            options={
                'ordering': ['cell_key'],
                'unique_together': {('zine', 'cell_key')},
            },
        ),
    ]
