# Generated by Django 6.0.4 on 2026-04-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zine',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
